### ISSUE TITLE
global to-do list

### ISSUE THREAD

**Issue by anastakozz** [anastakozz/graphiql-app#1]
**Sprint 1 (deadline 11.12.2023)**
- [x] setup repository
- [x] setup project
- [x] setup deployment (Vercel)
- [x] implement adaptive layout design-code
- [x] setup routes
- [x] implement Header and Footer
- [x] implement Welcome page
- [x] implement Sign In / Sign Up functionality
- [x] add localization

**Sprint 2 (deadline 18.12.2023)**
- [x] implement Main Page layout
- [x] add user-specified API endpoint selection
- [x] add request editor (query editor / JSON viewer)
- [x] add variables editor
- [x] add headers editor
- [x] add documentation explorer

**Sprint 3 (deadline 25.12.2023)**
- [x] finish documentation explorer
- [x] add prettifying to request editor
- [x] add API errors messages as popups
- [ ] add Proxy server handling non-CORS API
- [x] add user input validation  or error handling for request fields (additional)
- [x] add highlighting for request fields (additional)

**Sprint 4 (deadline 8.12.2023)**
- [ ] Fix all remaining bugs
- [x] complete 80% testing coverage
- [ ] ! Record final presentation video
